<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220329215101 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE utilisateur ADD country_id INT DEFAULT NULL, DROP country');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3F92F3E70 ON utilisateur (country_id)');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Afghanistan\',\'AF\',\'AFG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Albania\',\'AL\',\'ALB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Algeria\',\'DZ\',\'DZA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'American Samoa\',\'AS\',\'ASM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Andorra\',\'AD\',\'AND\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Angola\',\'AO\',\'AGO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Anguilla\',\'AI\',\'AIA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Antarctica\',\'AQ\',\'ATA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Antigua and Barbuda\',\'AG\',\'ATG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Argentina\',\'AR\',\'ARG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Armenia\',\'AM\',\'ARM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Aruba\',\'AW\',\'ABW\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Australia\',\'AU\',\'AUS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Austria\',\'AT\',\'AUT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Azerbaijan\',\'AZ\',\'AZE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bahamas (the)\',\'BS\',\'BHS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bahrain\',\'BH\',\'BHR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bangladesh\',\'BD\',\'BGD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Barbados\',\'BB\',\'BRB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Belarus\',\'BY\',\'BLR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Belgium\',\'BE\',\'BEL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Belize\',\'BZ\',\'BLZ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Benin\',\'BJ\',\'BEN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bermuda\',\'BM\',\'BMU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bhutan\',\'BT\',\'BTN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bolivia (Plurinational State of)\',\'BO\',\'BOL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bonaire, Sint Eustatius and Saba\',\'BQ\',\'BES\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bosnia and Herzegovina\',\'BA\',\'BIH\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Botswana\',\'BW\',\'BWA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bouvet Island\',\'BV\',\'BVT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Brazil\',\'BR\',\'BRA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'British Indian Ocean Territory (the)\',\'IO\',\'IOT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Brunei Darussalam\',\'BN\',\'BRN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Bulgaria\',\'BG\',\'BGR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Burkina Faso\',\'BF\',\'BFA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Burundi\',\'BI\',\'BDI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cabo Verde\',\'CV\',\'CPV\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cambodia\',\'KH\',\'KHM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cameroon\',\'CM\',\'CMR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Canada\',\'CA\',\'CAN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cayman Islands (the)\',\'KY\',\'CYM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Central African Republic (the)\',\'CF\',\'CAF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Chad\',\'TD\',\'TCD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Chile\',\'CL\',\'CHL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'China\',\'CN\',\'CHN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Christmas Island\',\'CX\',\'CXR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cocos (Keeling) Islands (the)\',\'CC\',\'CCK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Colombia\',\'CO\',\'COL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Comoros (the)\',\'KM\',\'COM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Congo (the Democratic Republic of the)\',\'CD\',\'COD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Congo (the)\',\'CG\',\'COG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cook Islands (the)\',\'CK\',\'COK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Costa Rica\',\'CR\',\'CRI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Croatia\',\'HR\',\'HRV\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cuba\',\'CU\',\'CUB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Curaçao\',\'CW\',\'CUW\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Cyprus\',\'CY\',\'CYP\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Czechia\',\'CZ\',\'CZE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Côte d\\\'Ivoire\',\'CI\',\'CIV\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Denmark\',\'DK\',\'DNK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Djibouti\',\'DJ\',\'DJI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Dominica\',\'DM\',\'DMA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Dominican Republic (the)\',\'DO\',\'DOM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Ecuador\',\'EC\',\'ECU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Egypt\',\'EG\',\'EGY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'El Salvador\',\'SV\',\'SLV\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Equatorial Guinea\',\'GQ\',\'GNQ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Eritrea\',\'ER\',\'ERI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Estonia\',\'EE\',\'EST\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Eswatini\',\'SZ\',\'SWZ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Ethiopia\',\'ET\',\'ETH\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Falkland Islands (the) [Malvinas]\',\'FK\',\'FLK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Faroe Islands (the)\',\'FO\',\'FRO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Fiji\',\'FJ\',\'FJI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Finland\',\'FI\',\'FIN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'France\',\'FR\',\'FRA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'French Guiana\',\'GF\',\'GUF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'French Polynesia\',\'PF\',\'PYF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'French Southern Territories (the)\',\'TF\',\'ATF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Gabon\',\'GA\',\'GAB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Gambia (the)\',\'GM\',\'GMB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Georgia\',\'GE\',\'GEO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Germany\',\'DE\',\'DEU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Ghana\',\'GH\',\'GHA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Gibraltar\',\'GI\',\'GIB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Greece\',\'GR\',\'GRC\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Greenland\',\'GL\',\'GRL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Grenada\',\'GD\',\'GRD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guadeloupe\',\'GP\',\'GLP\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guam\',\'GU\',\'GUM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guatemala\',\'GT\',\'GTM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guernsey\',\'GG\',\'GGY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guinea\',\'GN\',\'GIN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guinea-Bissau\',\'GW\',\'GNB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Guyana\',\'GY\',\'GUY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Haiti\',\'HT\',\'HTI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Heard Island and McDonald Islands\',\'HM\',\'HMD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Holy See (the)\',\'VA\',\'VAT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Honduras\',\'HN\',\'HND\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Hong Kong\',\'HK\',\'HKG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Hungary\',\'HU\',\'HUN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Iceland\',\'IS\',\'ISL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'India\',\'IN\',\'IND\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Indonesia\',\'ID\',\'IDN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Iran (Islamic Republic of)\',\'IR\',\'IRN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Iraq\',\'IQ\',\'IRQ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Ireland\',\'IE\',\'IRL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Isle of Man\',\'IM\',\'IMN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Israel\',\'IL\',\'ISR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Italy\',\'IT\',\'ITA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Jamaica\',\'JM\',\'JAM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Japan\',\'JP\',\'JPN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Jersey\',\'JE\',\'JEY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Jordan\',\'JO\',\'JOR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Kazakhstan\',\'KZ\',\'KAZ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Kenya\',\'KE\',\'KEN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Kiribati\',\'KI\',\'KIR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Korea (the Democratic People\\\'s Republic of)\',\'KP\',\'PRK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Korea (the Republic of)\',\'KR\',\'KOR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Kuwait\',\'KW\',\'KWT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Kyrgyzstan\',\'KG\',\'KGZ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Lao People\\\'s Democratic Republic (the)\',\'LA\',\'LAO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Latvia\',\'LV\',\'LVA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Lebanon\',\'LB\',\'LBN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Lesotho\',\'LS\',\'LSO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Liberia\',\'LR\',\'LBR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Libya\',\'LY\',\'LBY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Liechtenstein\',\'LI\',\'LIE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Lithuania\',\'LT\',\'LTU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Luxembourg\',\'LU\',\'LUX\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Macao\',\'MO\',\'MAC\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Madagascar\',\'MG\',\'MDG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Malawi\',\'MW\',\'MWI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Malaysia\',\'MY\',\'MYS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Maldives\',\'MV\',\'MDV\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mali\',\'ML\',\'MLI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Malta\',\'MT\',\'MLT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Marshall Islands (the)\',\'MH\',\'MHL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Martinique\',\'MQ\',\'MTQ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mauritania\',\'MR\',\'MRT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mauritius\',\'MU\',\'MUS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mayotte\',\'YT\',\'MYT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mexico\',\'MX\',\'MEX\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Micronesia (Federated States of)\',\'FM\',\'FSM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Moldova (the Republic of)\',\'MD\',\'MDA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Monaco\',\'MC\',\'MCO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mongolia\',\'MN\',\'MNG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Montenegro\',\'ME\',\'MNE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Montserrat\',\'MS\',\'MSR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Morocco\',\'MA\',\'MAR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Mozambique\',\'MZ\',\'MOZ\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Myanmar\',\'MM\',\'MMR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Namibia\',\'NA\',\'NAM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Nauru\',\'NR\',\'NRU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Nepal\',\'NP\',\'NPL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Netherlands (the)\',\'NL\',\'NLD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'New Caledonia\',\'NC\',\'NCL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'New Zealand\',\'NZ\',\'NZL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Nicaragua\',\'NI\',\'NIC\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Niger (the)\',\'NE\',\'NER\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Nigeria\',\'NG\',\'NGA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Niue\',\'NU\',\'NIU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Norfolk Island\',\'NF\',\'NFK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Northern Mariana Islands (the)\',\'MP\',\'MNP\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Norway\',\'NO\',\'NOR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Oman\',\'OM\',\'OMN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Pakistan\',\'PK\',\'PAK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Palau\',\'PW\',\'PLW\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Palestine, State of\',\'PS\',\'PSE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Panama\',\'PA\',\'PAN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Papua New Guinea\',\'PG\',\'PNG\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Paraguay\',\'PY\',\'PRY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Peru\',\'PE\',\'PER\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Philippines (the)\',\'PH\',\'PHL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Pitcairn\',\'PN\',\'PCN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Poland\',\'PL\',\'POL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Portugal\',\'PT\',\'PRT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Puerto Rico\',\'PR\',\'PRI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Qatar\',\'QA\',\'QAT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Republic of North Macedonia\',\'MK\',\'MKD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Romania\',\'RO\',\'ROU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Russian Federation (the)\',\'RU\',\'RUS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Rwanda\',\'RW\',\'RWA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Réunion\',\'RE\',\'REU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Barthélemy\',\'BL\',\'BLM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Helena, Ascension and Tristan da Cunha\',\'SH\',\'SHN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Kitts and Nevis\',\'KN\',\'KNA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Lucia\',\'LC\',\'LCA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Martin (French part)\',\'MF\',\'MAF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Pierre and Miquelon\',\'PM\',\'SPM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saint Vincent and the Grenadines\',\'VC\',\'VCT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Samoa\',\'WS\',\'WSM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'San Marino\',\'SM\',\'SMR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Sao Tome and Principe\',\'ST\',\'STP\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Saudi Arabia\',\'SA\',\'SAU\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Senegal\',\'SN\',\'SEN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Serbia\',\'RS\',\'SRB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Seychelles\',\'SC\',\'SYC\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Sierra Leone\',\'SL\',\'SLE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Singapore\',\'SG\',\'SGP\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Sint Maarten (Dutch part)\',\'SX\',\'SXM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Slovakia\',\'SK\',\'SVK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Slovenia\',\'SI\',\'SVN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Solomon Islands\',\'SB\',\'SLB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Somalia\',\'SO\',\'SOM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'South Africa\',\'ZA\',\'ZAF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'South Georgia and the South Sandwich Islands\',\'GS\',\'SGS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'South Sudan\',\'SS\',\'SSD\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Spain\',\'ES\',\'ESP\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Sri Lanka\',\'LK\',\'LKA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Sudan (the)\',\'SD\',\'SDN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Suriname\',\'SR\',\'SUR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Svalbard and Jan Mayen\',\'SJ\',\'SJM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Sweden\',\'SE\',\'SWE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Switzerland\',\'CH\',\'CHE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Syrian Arab Republic\',\'SY\',\'SYR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Taiwan (Province of China)\',\'TW\',\'TWN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Tajikistan\',\'TJ\',\'TJK\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Tanzania, United Republic of\',\'TZ\',\'TZA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Thailand\',\'TH\',\'THA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Timor-Leste\',\'TL\',\'TLS\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Togo\',\'TG\',\'TGO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Tokelau\',\'TK\',\'TKL\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Tonga\',\'TO\',\'TON\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Trinidad and Tobago\',\'TT\',\'TTO\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Tunisia\',\'TN\',\'TUN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Turkey\',\'TR\',\'TUR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Turkmenistan\',\'TM\',\'TKM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Turks and Caicos Islands (the)\',\'TC\',\'TCA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Tuvalu\',\'TV\',\'TUV\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Uganda\',\'UG\',\'UGA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Ukraine\',\'UA\',\'UKR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'United Arab Emirates (the)\',\'AE\',\'ARE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'United Kingdom of Great Britain and Northern Ireland (the)\',\'GB\',\'GBR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'United States Minor Outlying Islands (the)\',\'UM\',\'UMI\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'United States of America (the)\',\'US\',\'USA\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Uruguay\',\'UY\',\'URY\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Uzbekistan\',\'UZ\',\'UZB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Vanuatu\',\'VU\',\'VUT\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Venezuela (Bolivarian Republic of)\',\'VE\',\'VEN\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Viet Nam\',\'VN\',\'VNM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Virgin Islands (British)\',\'VG\',\'VGB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Virgin Islands (U.S.)\',\'VI\',\'VIR\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Wallis and Futuna\',\'WF\',\'WLF\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Western Sahara\',\'EH\',\'ESH\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Yemen\',\'YE\',\'YEM\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Zambia\',\'ZM\',\'ZMB\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Zimbabwe\',\'ZW\',\'ZWE\');');
        $this->addSql('INSERT INTO country VALUES(NULL,\'Åland Islands\',\'AX\',\'ALA\');');


    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE utilisateur DROP FOREIGN KEY FK_1D1C63B3F92F3E70');
        $this->addSql('DROP INDEX IDX_1D1C63B3F92F3E70 ON utilisateur');
        $this->addSql('ALTER TABLE utilisateur ADD country VARCHAR(255) DEFAULT NULL, DROP country_id');
    }
}
